language: python
os: linux

python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8

arch:
  - amd64
  - ppc64le

env:
    - BUILD=py

jobs:
    include:
      - python: 3.7
        env: BUILD=style
      - python: 3.7
        env: BUILD=docs
      - python: 3.7
        env: BUILD=mypy
      - python: 3.7
        env: BUILD=pytz201610
      - python: 3.7
        env: BUILD=pytz201702
        # Adding ppc64le jobs
      - python: 3.7
        arch: ppc64le
        env: BUILD=style
      - python: 3.7
        arch: ppc64le
        env: BUILD=docs
      - python: 3.7
        arch: ppc64le
        env: BUILD=mypy
      - python: 3.7
        arch: ppc64le
        env: BUILD=pytz201610
      - python: 3.7
        arch: ppc64le
        env: BUILD=pytz201702

addons:
    apt:
        packages:
            - language-pack-de

install:
        - "pip install tox"

script:
    - "tox -e $BUILD"
